version: '3.8'

services:
  watergame-api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - keys.env
    volumes:
      - .:/app
    restart: unless-stopped
    container_name: watergame-api

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - watergame-api
    restart: unless-stopped
    container_name: watergame-nginx

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file:
      - keys.env